services:
  - type: worker
    name: aplus-academy-telegram-bot
    env: python
    region: oregon
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: GROUP_ID
        sync: false
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_PORT
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_DATABASE
        sync: false
      - key: MYSQL_SSL_MODE
        value: REQUIRED
