services:
  - type: web
    name: aplus-academy-telegram-bot
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.14
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: PRIVATE_GROUP_ID
        sync: false
      - key: FALLBACK_GROUP_LINK
        value: https://t.me/+m6ikHXVS_ss0N2Vk
